spring:
  datasource:
    url: postgres://ec2-3-209-124-113.compute-1.amazonaws.com:5432/d9a7fkk3a5nsos
    username: hkpsebukospjzq
    password: 62560364e731eae7705a95c993c2af9ae84613bbd6788aa749da88e65cee2cf9
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: base
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: muhammadwidianto@gmail.com
    password: cprkcdsqcqwhleet

    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 30000
          timeout: 30000
    protocol: smtp
    test-connection: false